spring:
  application:
    name: boardgame-application
  
  # 데이터베이스 설정
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:boardgame.db
    username: sa
    password: password
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.boardgame.controller

# 로깅 설정
logging:
  level:
    root: INFO
    com.boardgame: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
